--SELECT * FROM TB_CLASS;
-- 
--SELECT * FROM TB_CLASS_PROFESSOR; 
--
--SELECT * FROM TB_DEPARTMENT; 
--
--SELECT * FROM TB_GRADE; 
--
--SELECT * FROM TB_PROFESSOR; 
--
--SELECT * FROM TB_STUDENT;


CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y',
    CONSTRAINT PK_1 PRIMARY KEY (NAME)
);

CREATE TABLE TB_CLASS_TYPE(

    NO VARCHAR2(5),
    NAME VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_DEPARTMENT1 PRIMARY KEY (NO)
    
);

-- 5번 
--ALTER TABLE TB_CLASS_TYPE
--MODIFY (NO VARCHAR2(10), NAME VARCHAR2(20));



-- 6번
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;


-- 7)
ALTER TABLE TB_CATEGORY
RENAME COLUMN CATEGORY_NAME TO PK_CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN CLASS_TYPE_NO TO PK_CLASS_TYPE_NO;

-- 8) 
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;


ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(PK_CATEGORY_NAME);

SELECT 과목번호, 과목이름, "누적수강생수(명)"
FROM (SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) "누적수강생수(명)"
      FROM TB_GRADE
           JOIN TB_CLASS USING(CLASS_NO)
      WHERE TERM_NO LIKE '2009%'
            OR TERM_NO LIKE '2008%'
            OR TERM_NO LIKE '2007%'
      GROUP BY CLASS_NO, CLASS_NAME
      ORDER BY 3 DESC)
WHERE ROWNUM <= 3;



