/*
CREATE TABLE JOB (
EMPNO NUMBER(4),
ENAME VARCHAR2(10),
JOB VARCHAR2(10),
DEPTNO NUMBER(2)
);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(001, '한여진', '경찰', 24);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(002, '황시목', '검사', 37);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(003, '강원철', '검사', 50);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(004, '장건', '경찰', 22);
 
INSERT INTO JOB (EMPNO, ENAME, JOB, DEPTNO)
VALUES(005, '이연재', 'CEO', 80);
 
SELECT * FROM JOB;

COMMIT;
*/

/*
CREATE TABLE CAFE(
    CAFEID NUMBER, 
    CAFENAME VARCHAR2(20), 
    CORPORATION VARCHAR2(20), 
    PRICE NUMBER
);

INSERT INTO CAFE (CAFEID, CAFENAME, CORPORATION, PRICE)
VALUES(14, '스타벅스', '신세계', 7000);

INSERT INTO CAFE (CAFEID, CAFENAME, CORPORATION, PRICE)
VALUES(20, '이디야', '이디야', 4500);

INSERT INTO CAFE (CAFEID, CAFENAME, CORPORATION, PRICE)
VALUES(3, '빽다방', '백종원', 3000);

SELECT * FROM CAFE;

COMMIT;
*/

/*
CREATE TABLE BEVERAGES(
    NAME VARCHAR2(30),
    PRICE NUMBER,
    BTYPE VARCHAR2(30)
);
INSERT INTO beverages(name, price, btype)
VALUES('아메리카노',   4500, 'COFFEE');
INSERT INTO beverages(name, price, btype)
VALUES('라떼',        5000, 'COFFEE');
INSERT INTO beverages(name, price, btype)
VALUES('카푸치노',     5000, 'COFFEE') ;
INSERT INTO beverages(name, price, btype)
VALUES ('카페모카',     5500, 'COFFEE');
INSERT INTO beverages(name, price, btype)
VALUES ('콜드브루',     5200, 'COFFEE');
INSERT INTO beverages(name, price, btype)
VALUES ('레몬 에이드',  3800, 'AID') ;
INSERT INTO beverages(name, price, btype)
VALUES   ('자몽 에이드',  4800, 'AID');
INSERT INTO beverages(name, price, btype)
VALUES ('바닐라 쉐이크', 5800, 'SHAKE');

SELECT * FROM BEVERAGES;
*/

/*
CREATE TABLE ORDER_DETAILS(
    ORDER_ID NUMBER,
    BEVERAGE_ID NUMBER,
    COUNT NUMBER
);

INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES(1,1,1);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES (2,  1, 2) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES(2,  2, 3) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES (2,  8, 2);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES  (3,  1, 2);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES  (4,  8, 1);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (5,  4, 1);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (6,  5, 3);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES    (7,  1, 3) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES  (7,  2, 2) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES    (8,  1, 1) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (9,  5, 1) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES (10, 1, 4)  ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES  (11, 2, 1)  ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (12, 3, 1) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES    (13, 1, 6);
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (14, 1, 8) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (14, 2, 2) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES   (14, 6, 1) ;
INSERT INTO ORDER_DETAILS(ORDER_ID, BEVERAGE_ID, COUNT)
VALUES  (15, 1, 4) ;



SELECT * FROM ORDER_DETAILS;

COMMIT;
*/
/*
CREATE TABLE TEST(
    ID VARCHAR2(20),
    PW VARCHAR2(20),
    NAME VARCHAR2(20)
);

SELECT * FROM TEST;
*/
